# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='quote_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='quote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.Quote'),
        ),
    ]
